;; Generated with ./domain-rubiks-cube/generator.py --output ./problems/problem7.pddl 7
(define
(problem rubiks-cube-shuffle-7)
(:domain rubiks-cube)
(:objects yellow white blue green orange red)
(:init
    (cube1 green white red)
    (cube2 white blue orange)
    (cube3 white red blue)
    (cube4 white green orange)
    (cube5 yellow red green)
    (cube6 green yellow orange)
    (cube7 blue yellow red)
    (cube8 yellow orange blue)
    (edge12 blue red)
    (edge24 white orange)
    (edge34 red yellow)
    (edge13 green white)
    (edge15 yellow green)
    (edge26 orange yellow)
    (edge48 yellow blue)
    (edge37 white blue)
    (edge56 red white)
    (edge68 green orange)
    (edge78 orange blue)
    (edge57 red green)
)
(:goal
    (and
        (cube1 red white blue)
        (cube2 orange white blue)
        (cube3 red yellow blue)
        (cube4 orange yellow blue)
        (cube5 red white green)
        (cube6 orange white green)
        (cube7 red yellow green)
        (cube8 orange yellow green)

        (edge12 white blue)
        (edge24 orange blue)
        (edge34 yellow blue)
        (edge13 red blue)

        (edge15 red white)
        (edge26 orange white)
        (edge48 orange yellow)
        (edge37 red yellow)

        (edge56 white green)
        (edge68 orange green)
        (edge78 yellow green)
        (edge57 red green)

    )
)
)
