;; Generated with ./domain-rubiks-cube/generator.py --output ./problems/problem8.pddl 8
(define
(problem rubiks-cube-shuffle-8)
(:domain rubiks-cube)
(:objects yellow white blue green orange red)
(:init
    (cube1 red green white)
    (cube2 green yellow red)
    (cube3 orange white blue)
    (cube4 red white blue)
    (cube5 red yellow blue)
    (cube6 orange yellow blue)
    (cube7 orange white green)
    (cube8 green orange yellow)
    (edge12 green white)
    (edge24 green red)
    (edge34 white blue)
    (edge13 green orange)
    (edge15 white orange)
    (edge26 orange yellow)
    (edge48 blue red)
    (edge37 red yellow)
    (edge56 white red)
    (edge68 orange blue)
    (edge78 blue yellow)
    (edge57 green yellow)
)
(:goal
    (and
        (cube1 red white blue)
        (cube2 orange white blue)
        (cube3 red yellow blue)
        (cube4 orange yellow blue)
        (cube5 red white green)
        (cube6 orange white green)
        (cube7 red yellow green)
        (cube8 orange yellow green)

        (edge12 white blue)
        (edge24 orange blue)
        (edge34 yellow blue)
        (edge13 red blue)

        (edge15 red white)
        (edge26 orange white)
        (edge48 orange yellow)
        (edge37 red yellow)

        (edge56 white green)
        (edge68 orange green)
        (edge78 yellow green)
        (edge57 red green)

    )
)
)
