;; Generated with ./domain-rubiks-cube/generator.py --output ./problems/problem13.pddl 13
(define
(problem rubiks-cube-shuffle-13)
(:domain rubiks-cube)
(:objects yellow white blue green orange red)
(:init
    (cube1 green red yellow)
    (cube2 green red white)
    (cube3 yellow orange blue)
    (cube4 blue yellow red)
    (cube5 white blue orange)
    (cube6 white green orange)
    (cube7 red white blue)
    (cube8 green orange yellow)
    (edge12 green orange)
    (edge24 green white)
    (edge34 green yellow)
    (edge13 red blue)
    (edge15 orange white)
    (edge26 red white)
    (edge48 yellow orange)
    (edge37 blue white)
    (edge56 red yellow)
    (edge68 orange blue)
    (edge78 red green)
    (edge57 blue yellow)
)
(:goal
    (and
        (cube1 red white blue)
        (cube2 orange white blue)
        (cube3 red yellow blue)
        (cube4 orange yellow blue)
        (cube5 red white green)
        (cube6 orange white green)
        (cube7 red yellow green)
        (cube8 orange yellow green)

        (edge12 white blue)
        (edge24 orange blue)
        (edge34 yellow blue)
        (edge13 red blue)

        (edge15 red white)
        (edge26 orange white)
        (edge48 orange yellow)
        (edge37 red yellow)

        (edge56 white green)
        (edge68 orange green)
        (edge78 yellow green)
        (edge57 red green)

    )
)
)
