;; Generated with ./domain-rubiks-cube/generator.py --output ./problems/problem11.pddl 11
(define
(problem rubiks-cube-shuffle-11)
(:domain rubiks-cube)
(:objects yellow white blue green orange red)
(:init
    (cube1 yellow blue orange)
    (cube2 yellow blue red)
    (cube3 green white orange)
    (cube4 red yellow green)
    (cube5 red blue white)
    (cube6 white red green)
    (cube7 orange green yellow)
    (cube8 white blue orange)
    (edge12 blue red)
    (edge24 white green)
    (edge34 yellow green)
    (edge13 yellow red)
    (edge15 yellow blue)
    (edge26 yellow orange)
    (edge48 white blue)
    (edge37 green red)
    (edge56 green orange)
    (edge68 white orange)
    (edge78 blue orange)
    (edge57 white red)
)
(:goal
    (and
        (cube1 red white blue)
        (cube2 orange white blue)
        (cube3 red yellow blue)
        (cube4 orange yellow blue)
        (cube5 red white green)
        (cube6 orange white green)
        (cube7 red yellow green)
        (cube8 orange yellow green)

        (edge12 white blue)
        (edge24 orange blue)
        (edge34 yellow blue)
        (edge13 red blue)

        (edge15 red white)
        (edge26 orange white)
        (edge48 orange yellow)
        (edge37 red yellow)

        (edge56 white green)
        (edge68 orange green)
        (edge78 yellow green)
        (edge57 red green)

    )
)
)
