;; Generated with ./domain-rubiks-cube/generator.py --output ./problems/problem5.pddl 5
(define
(problem rubiks-cube-shuffle-5)
(:domain rubiks-cube)
(:objects yellow white blue green orange red)
(:init
    (cube1 blue orange yellow)
    (cube2 yellow blue red)
    (cube3 white red blue)
    (cube4 orange green yellow)
    (cube5 green red white)
    (cube6 red yellow green)
    (cube7 green orange white)
    (cube8 blue orange white)
    (edge12 orange yellow)
    (edge24 yellow red)
    (edge34 red blue)
    (edge13 white blue)
    (edge15 red white)
    (edge26 orange blue)
    (edge48 blue yellow)
    (edge37 green orange)
    (edge56 yellow green)
    (edge68 red green)
    (edge78 orange white)
    (edge57 green white)
)
(:goal
    (and
        (cube1 red white blue)
        (cube2 orange white blue)
        (cube3 red yellow blue)
        (cube4 orange yellow blue)
        (cube5 red white green)
        (cube6 orange white green)
        (cube7 red yellow green)
        (cube8 orange yellow green)

        (edge12 white blue)
        (edge24 orange blue)
        (edge34 yellow blue)
        (edge13 red blue)

        (edge15 red white)
        (edge26 orange white)
        (edge48 orange yellow)
        (edge37 red yellow)

        (edge56 white green)
        (edge68 orange green)
        (edge78 yellow green)
        (edge57 red green)

    )
)
)
