;; Generated with ./domain-rubiks-cube/generator.py --output ./problems/problem6.pddl 6
(define
(problem rubiks-cube-shuffle-6)
(:domain rubiks-cube)
(:objects yellow white blue green orange red)
(:init
    (cube1 blue white orange)
    (cube2 white red blue)
    (cube3 yellow red green)
    (cube4 green orange white)
    (cube5 red white green)
    (cube6 red blue yellow)
    (cube7 orange yellow blue)
    (cube8 green orange yellow)
    (edge12 red blue)
    (edge24 white blue)
    (edge34 orange white)
    (edge13 blue orange)
    (edge15 red white)
    (edge26 orange green)
    (edge48 green yellow)
    (edge37 yellow red)
    (edge56 blue yellow)
    (edge68 white green)
    (edge78 orange yellow)
    (edge57 red green)
)
(:goal
    (and
        (cube1 red white blue)
        (cube2 orange white blue)
        (cube3 red yellow blue)
        (cube4 orange yellow blue)
        (cube5 red white green)
        (cube6 orange white green)
        (cube7 red yellow green)
        (cube8 orange yellow green)

        (edge12 white blue)
        (edge24 orange blue)
        (edge34 yellow blue)
        (edge13 red blue)

        (edge15 red white)
        (edge26 orange white)
        (edge48 orange yellow)
        (edge37 red yellow)

        (edge56 white green)
        (edge68 orange green)
        (edge78 yellow green)
        (edge57 red green)

    )
)
)
