;; Generated with ./domain-rubiks-cube/generator.py --output ./problems/problem9.pddl 9
(define
(problem rubiks-cube-shuffle-9)
(:domain rubiks-cube)
(:objects yellow white blue green orange red)
(:init
    (cube1 yellow green red)
    (cube2 green white orange)
    (cube3 yellow orange blue)
    (cube4 green yellow orange)
    (cube5 blue red yellow)
    (cube6 white blue red)
    (cube7 red green white)
    (cube8 white blue orange)
    (edge12 red blue)
    (edge24 white red)
    (edge34 yellow orange)
    (edge13 blue white)
    (edge15 blue yellow)
    (edge26 green white)
    (edge48 green yellow)
    (edge37 red yellow)
    (edge56 red green)
    (edge68 orange green)
    (edge78 blue orange)
    (edge57 white orange)
)
(:goal
    (and
        (cube1 red white blue)
        (cube2 orange white blue)
        (cube3 red yellow blue)
        (cube4 orange yellow blue)
        (cube5 red white green)
        (cube6 orange white green)
        (cube7 red yellow green)
        (cube8 orange yellow green)

        (edge12 white blue)
        (edge24 orange blue)
        (edge34 yellow blue)
        (edge13 red blue)

        (edge15 red white)
        (edge26 orange white)
        (edge48 orange yellow)
        (edge37 red yellow)

        (edge56 white green)
        (edge68 orange green)
        (edge78 yellow green)
        (edge57 red green)

    )
)
)
