;; Generated with ./generator.py --output problem2.pddl 100
(define
(problem rubiks-cube-shuffle-100)
(:domain rubiks-cube)
(:objects yellow white blue green orange red)
(:init
    (cube1 yellow orange green)
    (cube2 yellow orange blue)
    (cube3 white blue orange)
    (cube4 red yellow green)
    (cube5 green red white)
    (cube6 blue red white)
    (cube7 white green orange)
    (cube8 red yellow blue)
    (edge12 orange green)
    (edge24 white green)
    (edge34 white red)
    (edge13 white orange)
    (edge15 red yellow)
    (edge26 yellow blue)
    (edge48 blue red)
    (edge37 orange blue)
    (edge56 green red)
    (edge68 white blue)
    (edge78 orange yellow)
    (edge57 yellow green)
)
(:goal
    (and
        (cube1 red white blue)
        (cube2 orange white blue)
        (cube3 red yellow blue)
        (cube4 orange yellow blue)
        (cube5 red white green)
        (cube6 orange white green)
        (cube7 red yellow green)
        (cube8 orange yellow green)

        (edge12 white blue)
        (edge24 orange blue)
        (edge34 yellow blue)
        (edge13 red blue)

        (edge15 red white)
        (edge26 orange white)
        (edge48 orange yellow)
        (edge37 red yellow)

        (edge56 white green)
        (edge68 orange green)
        (edge78 yellow green)
        (edge57 red green)

    )
)
)
