;; Generated with generator.py --output problem.pddl 10
(define
(problem rubiks-cube-shuffle-10)
(:domain rubiks-cube)
(:objects yellow white blue green orange red)
(:init
    (cube1 red white blue)
    (cube2 yellow blue red)
    (cube3 white green red)
    (cube4 yellow blue orange)
    (cube5 white blue orange)
    (cube6 yellow orange green)
    (cube7 orange white green)
    (cube8 red green yellow)
    (edge12 green white)
    (edge24 yellow red)
    (edge34 green yellow)
    (edge13 blue yellow)
    (edge15 white orange)
    (edge26 orange blue)
    (edge48 red green)
    (edge37 white red)
    (edge56 orange green)
    (edge68 blue white)
    (edge78 blue red)
    (edge57 orange yellow)
)
(:goal
    (and
        (cube1 red white blue)
        (cube2 orange white blue)
        (cube3 red yellow blue)
        (cube4 orange yellow blue)
        (cube5 red white green)
        (cube6 orange white green)
        (cube7 red yellow green)
        (cube8 orange yellow green)

        (edge12 white blue)
        (edge24 orange blue)
        (edge34 yellow blue)
        (edge13 red blue)

        (edge15 red white)
        (edge26 orange white)
        (edge48 orange yellow)
        (edge37 red yellow)

        (edge56 white green)
        (edge68 orange green)
        (edge78 yellow green)
        (edge57 red green)

    )
)
)
